CREATE OR REPLACE PROCEDURE PRC_PROD_DISCOUNT
AS BEGIN
   UPDATE PRODUCT
     SET P_DISCOUNT = P_DISCOUNT + .05
       WHERE P_ONHAND >= P_MIN*2;
   DBMS_OUTPUT.PUT_LINE ('* * Update finished * *');
END;


