NAME = Sockets
JC = jikes
FILES = arp_msg.java ClientGUI.java clientThread.java gateway.java ipLookupTable.java list.java msg.java msgThread.java

all:$(NAME)

$(NAME):$(FILES)
	$(JC) $(FILES)

clean:
	rm *.class

