NAME = Sockets
JC = javac
FILES=AccessLayer.java client.java REQ_MSG.java REP_MSG.java serverThread.java Protection.java GUI.java validate.java

all:$(NAME)

$(NAME):$(FILES)
	$(JC) $(FILES)

clean:
	rm *.class

