IF EXISTS (SELECT name FROM sysobjects 
   WHERE name = 'PRC_INV_ADD' AND type = 'P')
   DROP PROCEDURE PRC_INV_ADD
GO
CREATE PROCEDURE PRC_INV_ADD
@W_INV_NUM INTEGER,
@W_CUS_CODE INTEGER,
@W_DATE DATETIME
AS
BEGIN
   INSERT INTO INVOICE (INV_NUMBER, CUS_CODE, INV_DATE)
          VALUES(@W_INV_NUM, @W_CUS_CODE, @W_DATE);
   PRINT('Invoice added');
END;
