


# Note: on some machines you have to specify a special library
# to get a version of malloc/free with acceptable performance


learn-dfa: learn-dfa.c data-structures.c data-structures.h
	gcc -O2 -Wall -o learn-dfa learn-dfa.c data-structures.c
