:  CH11 - ORACLE OBJECT SUPPORT 
:  SQL code to show OO support within Oracle 9i

: DELETE OLD OBJECTS AND TABLES
DROP TABLE OTBL_JOBHISTORY;
DROP TABLE WORKER;
DROP TYPE T_JOB;
DROP TYPE T_ADDRESS;
DROP TABLE OTBL_BAND;
DROP TYPE T_MUSICIAN;




: Create Column Type (User-Defined Data) T_ADDRESS
CREATE OR REPLACE TYPE T_ADDRESS AS OBJECT (
STREET    VARCHAR2(20),
CITY      VARCHAR2(15),
STATE     CHAR(2),
ZIP       CHAR(5)
);
/

: Create User-Defined Data Type T_JOB
CREATE OR REPLACE TYPE T_JOB AS OBJECT (
CNAME		VARCHAR(15),
START_DATE 	DATE,
END_DATE   	DATE,
MONTHLYSALARY	NUMBER(7,2),
MEMBER FUNCTION MONTHSONJOB RETURN NUMBER,
MEMBER FUNCTION TOTALEARNED RETURN NUMBER
);
/

: Create the T_JOB Methods
CREATE OR REPLACE TYPE BODY T_JOB AS
 MEMBER FUNCTION MONTHSONJOB RETURN NUMBER IS
  BEGIN
    RETURN TRUNC(((SELF.END_DATE - SELF.START_DATE)/30),1);
  END;
 MEMBER FUNCTION TOTALEARNED RETURN NUMBER IS
  BEGIN
   RETURN(MONTHSONJOB*SELF.MONTHLYSALARY);
  END;
END ;
/


: Create a WORKER table using the T_ADDRESS AND T_JOB ADT
CREATE TABLE WORKER(
WRK_NUM     NUMBER PRIMARY KEY,
WRK_LNAME   VARCHAR2(15) NOT NULL,
WRK_FNAME   VARCHAR2(15) NOT NULL,
WRK_ADDRESS T_ADDRESS,
WRK_PREVJOB T_JOB);


: INSERT DATA

INSERT INTO WORKER 
VALUES (1,'VILLEGAS','ROBERTO',
        T_ADDRESS('123 Main St.','London','OH','76987'), 
        T_JOB('GLOBALCOM','01-AUG-1999','03-DEC-2002',3000));

INSERT INTO WORKER 
VALUES (2,'GORTTY','JANE',
        T_ADDRESS('453 Sulla St.','London','OH','76987'), 
        T_JOB('SURESTART','15-MAY-2000','15-OCT-2002',2500));

INSERT INTO WORKER 
VALUES (3,'SMITH','MARGO',
        T_ADDRESS('7854 Court Av.','London','OH','76984'), 
        T_JOB('TELCO-R-US','01-JUL-2001','15-SEP-2002',4000));


: SELECT DATA FROM TABLE
SELECT 	WRK_FNAME || ', ' || WRK_LNAME 	AS NAME,
        W.WRK_ADDRESS.STREET           	AS STREET,
        W.WRK_ADDRESS.CITY		AS CITY,
        W.WRK_ADDRESS.STATE		AS STATE,
        W.WRK_PREVJOB.MONTHSONJOB()	AS MONTHS,
        W.WRK_PREVJOB.TOTALEARNED()	AS TOTAL
FROM    WORKER W;


=================================================
: ROW TYPE OBJECTS

CREATE TYPE T_MUSICIAN AS OBJECT (
NAME            VARCHAR(15),
DOB             DATE,
INSTRUMENT      CHAR(8),
MEMBER FUNCTION AGE RETURN NUMBER
);
/

: Create the T_MUSICIAN Methods
CREATE OR REPLACE TYPE BODY T_MUSICIAN AS
 MEMBER FUNCTION AGE RETURN NUMBER IS
  BEGIN
    RETURN TRUNC(((SYSDATE - SELF.DOB)/365),1);
  END;
END ;
/

: CREATE OBJECT TABLE
CREATE TABLE OTBL_BAND OF T_MUSICIAN OBJECT ID IS SYSTEM GENERATED;

: INSERT DATA
INSERT INTO OTBL_BAND 
VALUES ('TOM JONES','01-AUG-1943','SINGER');

INSERT INTO OTBL_BAND
VALUES ('FLEETWOD MAC','15-MAY-1940','DRUMS');

INSERT INTO OTBL_BAND 
VALUES ('JIMY HENDRIX','01-JUL-1928','GUITAR');


: SELECT DATA FROM TABLE
SELECT 	NAME, DOB, INSTRUMENT, B.AGE()	AS AGE
FROM   	OTBL_BAND B;

=================================================
: VARRAY

: CREATE VARRAY OBJECT TYPE
CREATE TYPE T_DEPENDLIST AS VARRAY(10) OF VARCHAR(10);
/

: CREATE TABLE EMP3 USING VARRAY TYPE
CREATE TABLE EMP3 (
E_LNAME        VARCHAR(15),
E_FNAME        VARCHAR(15),
E_DEPENDENTS   T_DEPENDLIST
);

: INSERT DATA
INSERT INTO EMP3 
VALUES ('SMITH','ALAN',T_DEPENDLIST('STAN','MARY'));

INSERT INTO EMP3 
VALUES ('PRATT','ALYSSA',T_DEPENDLIST('CARLOS','PETER','DEB'));


: SELECT DATA FROM TABLE
SELECT 	E_LNAME, E_FNAME, E_DEPENDENTS
FROM   	EMP3 E;

======================================
:NESTED TABLES

: CREATE TYPE T_DEPDNT 
CREATE TYPE T_DEPDNT AS OBJECT (
NAME   VARCHAR(12)
)
/

: CREATE THE TABLE TYPE
CREATE TYPE T_DEPTAB AS TABLE OF T_DEPDNT;


: CRATE A TABLE THAT USES NESTED TABLE TYPE
CREATE TABLE EMP4 (
E_LNAME        VARCHAR(15),
E_FNAME        VARCHAR(15),
E_DEPENDENTS   T_DEPTAB)
NESTED TABLE E_DEPENDENTS STORE AS DEPTABLE;

: ADD ROWS
INSERT INTO EMP4 
VALUES ('SMITH','ALAN',T_DEPTAB(T_DEPDNT('STAN'),T_DEPDNT('BILL')));

INSERT INTO EMP4 
VALUES ('PRATT','ALYSSA',T_DEPTAB(T_DEPDNT('CARLOS'),T_DEPDNT('PETER'),T_DEPDNT('DEB')));

: LIST DATA
SELECT * FROM EMP4;



