NAME = VoIP
JC = jikes
FILES = UAS.java UAC.java Registrar.java SIP.java ProxyServer.java VoIP.java gui.java list.java speaker.java microphone.java

all:$(NAME)

$(NAME):$(FILES)
	$(JC) $(FILES)

clean:
	rm *.class

