CREATE OR REPLACE TRIGGER TRG_PRODUCT_REORDER
BEFORE INSERT OR UPDATE OF P_ONHAND, P_MIN ON PRODUCT
FOR EACH ROW
BEGIN
   IF :NEW.P_ONHAND <= :NEW.P_MIN THEN
	:NEW.P_REORDER := 1;
   ELSE
        :NEW.P_REORDER := 0;
   END IF;
END;

