<HTML>
<HEAD>
<TITLE>Rob & Coronel -  ColdFusion Examples</TITLE>
<CFQUERY NAME="VENDATA" DATASOURCE="RobCor">
        SELECT * FROM VENDOR ORDER BY VEN_CODE
</CFQUERY>
</HEAD>
<BODY BGCOLOR="LIGHTBLUE">
<H1>
<B><CENTER>Simple Query Using CFQUERY and CFTABLE</CENTER></B>
</H1>
<BR>
<TABLE BGCOLOR="Silver" BORDERCOLOR="Fuchsia" FRAME="BORDER">
<TR><HR></TR>
<TR>
<CFTABLE QUERY="VENDATA" STARTROW="1" COLSPACING="1" COLHEADERS>
<CFCOL HEADER="<B>CODE</B>" WIDTH="8" TEXT="#VEN_CODE#">
<CFCOL HEADER="<B>VENDOR_NAME</B>" WIDTH="25" TEXT="#VEN_NAME#">
<CFCOL HEADER="<B>CONTACT_PERSON</B>" WIDTH="14" TEXT="#VEN_CONTACT_NAME#">
<CFCOL HEADER="<B>ADDRESS</B>" WIDTH="20" TEXT="#VEN_ADDRESS#">
<CFCOL HEADER="<B>CITY</B>" WIDTH="10" TEXT="#VEN_CITY#">
<CFCOL HEADER="<B>STATE</B>" WIDTH="2" TEXT="#VEN_STATE#">
<CFCOL HEADER="<B>ZIP</B>" WIDTH="5" TEXT="#VEN_ZIP#">
<CFCOL HEADER="<B>PHONE</B>" WIDTH="10" TEXT="#VEN_PH#">
<CFCOL HEADER="<B>FAX</B>" WIDTH="10" TEXT="#VEN_FAX#">
<CFCOL HEADER="<B>E-MAIL</B>" WIDTH="10" TEXT="#VEN_EMAIL#">
<CFCOL HEADER="<B>CUSTOMER_ID</B>" WIDTH="8" TEXT="#VEN_CUS_ID#">
<CFCOL HEADER="<B>SUPPORT_PHONE</B>" WIDTH="6" TEXT="#VEN_SUPPORT_ID#">
<CFCOL HEADER="<B>WEB PAGE</B>" WIDTH="14" TEXT="#VEN_WEB_PAGE#">
</CFTABLE>
</TR>
<TR>
<FORM ACTION="rc-0.cfm" METHOD="post">
	<INPUT TYPE="submit" VALUE="Main Menu ">
</FORM>
</TR>
</TABLE>
</BODY>
</HTML>


