<HTML>
<CFQUERY NAME="SearchVendor" DATASOURCE="RobCor">
	SELECT VEN_CODE, VEN_NAME, VEN_CONTACT_NAME, VEN_ADDRESS, VEN_CITY, VEN_STATE, VEN_PH
	FROM VENDOR
	WHERE 0=0
    <CFIF #FORM.VEN_CODE# IS NOT "">
		AND VENDOR.VEN_CODE LIKE '%#FORM.VEN_CODE#%'
	</CFIF>	
    <CFIF #FORM.VEN_STATE# IS NOT "ANY">
        AND VENDOR.VEN_STATE LIKE '%#FORM.VEN_STATE#%'
	</CFIF>
    ORDER BY VEN_CODE
</CFQUERY>
<HEAD>
<TITLE>Rob & Coronel -  ColdFusion Examples</TITLE>
</HEAD>
<BODY BGCOLOR="LIGHTBLUE">
<H1>
<CENTER><B>Vendor Search Results</B></CENTER>
</H1>
<BR>
<CFTABLE QUERY="SearchVendor" STARTROW="1" COLSPACING="1" COLHEADERS>
<CFCOL HEADER="<B>VENDOR CODE</B>" WIDTH="14" TEXT="#VEN_CODE#">
<CFCOL HEADER="<B>VENDOR NAME</B>" WIDTH="20" TEXT="#VEN_NAME#">
<CFCOL HEADER="<B>CONTACT PERSON</B>" WIDTH="20" TEXT="#VEN_CONTACT_NAME#">
<CFCOL HEADER="<B>ADDRESS</B>" WIDTH="20" TEXT="#VEN_ADDRESS#">
<CFCOL HEADER="<B>CITY</B>" WIDTH="20" TEXT="#VEN_CITY#">
<CFCOL HEADER="<B>STATE</B>" WIDTH="2" TEXT="#VEN_STATE#">
<CFCOL HEADER="<B>PHONE</B>" WIDTH="20" TEXT="#VEN_PH#">
</CFTABLE>
<CFIF #SEARCHVENDOR.RECORDCOUNT# IS 0>
  	<H2>No records were found matching your criteria </H2>
<CFELSE>
	<CFOUTPUT>Your seach returned #SearchVendor.RecordCount# record(s).</CFOUTPUT>
</CFIF>
<FORM ACTION="rc-0.cfm" METHOD="post">
	<INPUT TYPE="submit" VALUE="Main Menu ">
</FORM>
</BODY>
</HTML>


